all: exercise_1.1.exe exercise_1.2.exe exercise_1.3.exe exercise_1.4.exe exercise_1.5.exe exercise_1.6.exe exercise_1.7.exe exercise_1.8.exe exercise_1.9.exe exercise_1.10.exe

exercise_1.1.exe: exercise_1.1.f90
	gfortran -o exercise_1.1.exe exercise_1.1.f90

exercise_1.2.exe: exercise_1.2.f90
	gfortran -o exercise_1.2.exe exercise_1.2.f90

exercise_1.3.exe: exercise_1.3.f90
	gfortran -o exercise_1.3.exe exercise_1.3.f90

exercise_1.4.exe: exercise_1.4.f90
	gfortran -o exercise_1.4.exe exercise_1.4.f90

exercise_1.5.exe: exercise_1.5.f90
	gfortran -o exercise_1.5.exe exercise_1.5.f90

exercise_1.6.exe: exercise_1.6.f90
	gfortran -o exercise_1.6.exe exercise_1.6.f90

exercise_1.7.exe: exercise_1.7.f90
	gfortran -o exercise_1.7.exe exercise_1.7.f90

exercise_1.8.exe: exercise_1.8.f90
	gfortran -o exercise_1.8.exe exercise_1.8.f90

exercise_1.9.exe: exercise_1.9.f90
	gfortran -o exercise_1.9.exe exercise_1.9.f90

exercise_1.10.exe: exercise_1.10.f90
	gfortran -o exercise_1.10.exe exercise_1.10.f90

clean:
	rm -f *.out *.exe *.o *.mod