all: exercise_2.1.exe exercise_2.2.exe exercise_2.3.exe exercise_2.4.exe exercise_2.5.exe exercise_2.6.exe exercise_2.7.exe exercise_2.8.exe
	rm -f *.o 

exercise_2.1.exe:
	gfortran -o exercise_2.1.exe exercise_2.1.f90

exercise_2.2.exe:
	gfortran -o exercise_2.2.exe exercise_2.2.f90

exercise_2.3.exe:
	gfortran -o exercise_2.3.exe exercise_2.3.f90

exercise_2.4.exe:
	gfortran -o exercise_2.4.exe exercise_2.4.f90

exercise_2.5.exe:
	gfortran -o exercise_2.5.exe exercise_2.5.f90

exercise_2.6.exe:
	gfortran -o exercise_2.6.exe exercise_2.6.f90

exercise_2.7.exe:
	gfortran -o exercise_2.7.exe exercise_2.7.f90

exercise_2.8.exe:
	gfortran -o exercise_2.8.exe exercise_2.8.f90

clean:
	rm -f *.o *.exe